### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [0xCAB0/shor_algorithm#1]
I recently came across your project shor_algorithm and I noticed that the repository github.com/0xCAB0/shor_algorithm currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by 0xCAB0** [comment]
Hi, we'd like to license the project for educational use only. What license would you recommend? 
Ty for displaying this issue, we didn't really have it in mind.

**Comment by cbjuan** [comment]
I cannot advise you about a exact license you should use. In any case, you can check out this GitHub's website to choose a license (linked from the documentation I shared in the issue). https://choosealicense.com/

Thanks
